### PR TITLE
Re-add style check, typecheck, integrationtests

### LINKED ISSUE #2: Analyze phpstan-higher-order-collections
Let's run PHPStan on ourselves!

At least with `--level=max`

### LINKED ISSUE #3: Add CI
May I set up TravisCI with the following?

- Check CS
- Run unit tests
- #2

### PR DESCRIPTION
**Pull request by nmokkenstorm**
closes #2 , closes #3

### CODE REVIEW

**Comment by szepeviktor** [comment]
PHPStan calls its plugins [extensions](https://phpstan.org/user-guide/extension-library).

You could go with `namespace SustainabilIT\PHPStan\HOC;`

**Comment by szepeviktor** [comment]
And `/Extensions` are really `/Services`, see https://github.com/Sustainabil-IT/phpstan-higher-order-collections/blob/main/extension.neon#L16

**Comment by nmokkenstorm** [comment]
> namespace SustainabilIT\PHPStan\HOC

This is actually a great idea. I briefly considered using PHPStan as vendor prefix, but that felt a bit weird as I don't actually speak for @ondrejmirtes

> And `/Extensions` are really `/Services`

I called them Extensions because they satisfy the *Extension interfaces that PHPStan supplies for extension development, but I honestly don't have a strong preference either way. 'Services' feels a bit too general for my taste, ideally I'd move some of the things out of the Reflections folder to their own spot too.

**Comment by szepeviktor** [comment]
> using PHPStan as vendor prefix

_smart_ guys do that :) https://github.com/szepeviktor/phpstan-wordpress/blob/master/src/RedirectCanonicalDynamicFunctionReturnTypeExtension.php#L9

**Pull request merged**
